In [1]:
import numpy as np

In [ ]:
#Use numpy to generate array of 25 random numbers sampled from a standard normal distribution

In [3]:
a=np.random.randn(25)
a

array([ 1.01743009,  0.50642673,  0.74005766, -0.00576254, -1.45019701,
        0.23401951,  1.09390743,  0.6146521 , -1.41045775,  0.14435603,
       -1.94038123, -0.21290823,  0.94046258,  0.35726631, -1.86097385,
       -1.8796086 ,  0.07401531, -0.32734958, -1.45887583, -0.20580528,
        0.39750544,  0.56610031, -1.10650276, -0.0396626 ,  0.83298731])

In [ ]:
#Create a random vector of size 30 and find the mean value.

In [6]:
a=np.random.randint(low=0,high=100,size=30)
b=np.mean(a)
b

45.03333333333333

In [ ]:
#Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.

In [10]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
a=np.random.randint(low=0,high=200,size=(10,10))
np.min(a)

0

In [24]:
b=np.random.randint(low=0,high=200,size=(10,10))
np.max(b)

199

In [25]:
#Find Dot product of two arrays

f = np.array([1,2])

g = np.array([4,5])
np.dot(f,g)

14

In [28]:
#Concatenate following arrays along axis=0

x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

In [29]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [44]:
print(np.intersect1d(a,b))

[  0   8  11  12  16  28  63  72  89 100 105 109 118 127 129 134 146 151
 163 174 176 184 195 199]


In [49]:
#Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  7,  8, 10])